### ISSUE TITLE
Search across collections

### ISSUE THREAD

**Issue by DanCoughlin** [psu-libraries/cho#10]
As a user,
I would like to search across the collections and objects not in collections,
So that I can find everything related to the topic outside of the collection I am viewing.

User should easily be able to add/remove collections from the search scope. What collections a user is searching should be prominently displayed.

As an end user, if I’m using search I just want to be able to put in someone’s name and find the thing I’m looking for. [Ruth K-T]

**Comment by informaticianme** [comment]
Collection name should be a facet.

**Comment by ntallman** [comment]
Done!
