### ISSUE TITLE
Search content type

### ISSUE THREAD

**Issue by DanCoughlin** [psu-libraries/cho#11]
As a user,
I would like to limit my search results by format (i.e. video, audio),
So that I can find format specific content.

**Comment by ntallman** [comment]
Hyrax does some of this, but not sure what field it will pull from. Ideally, we will map several mime-types to a genre or format to aid the user.

**Comment by ntallman** [comment]
Is this achieved with work types?

**Comment by ntallman** [comment]
Considering this achieved through work types.
