### ISSUE TITLE
Deleting Works, Individually and Batch

### ISSUE THREAD

**Issue by ntallman** [psu-libraries/cho#119]
As a collection curator
I need to delete images and their metadata individually or in batch 
So that I can improve the quality of the collection

Stephanie M.

**Comment by ntallman** [comment]
Should have the option to create tombstone

**Comment by awead** [comment]
Steps:
1. Implement an accessible interface to delete a single with a user confirmation
2. Implement an accessible interface to delete multiple works with a user confirmation
