### ISSUE TITLE
Index Filenames

### ISSUE THREAD

**Issue by ntallman** [psu-libraries/cho#122]
As a remote researcher,
I would like filenames to be indexed,
So that if I forget where I downloaded a file, I can search on the filename and find the record.

Related: #77

**Comment by awead** [comment]
@ntallman if we follow the hyrax/sufia paradigm, files themselves are not indexed; therefore, they aren't returned as a search result.  When searching for filenames, file contents, or any other technical information about it, I'd get back the work and not the individual file. Is this what you'd expect for CHO?

**Comment by ntallman** [comment]
Getting back the work is A-OK to accomplish this user story in CHO.

**Comment by mtribone** [comment]
Might need to close this ticket, but need to double check after we incorporate filesets. You will be able to search on file names, but the work will be returned in search results.

**Comment by awead** [comment]
Done looks like:
* I type in the name of a file that was uploaded via bag, and I get back the work.
