### ISSUE TITLE
Search Files Attached to an Object

### ISSUE THREAD

**Issue by ntallman** [psu-libraries/cho#135]
As a researcher, 
I would like to search within a compound object like a digitized book, 
so that I can locate a specific term within a large object.

Ben G.

Related to #545

**Comment by mtribone** [comment]
Search the text within the file. Imply we have uploaded a file that has discrete text and not generated. Part of the overarching search. How are we saying this has been found? What is the desired result. For MVP just the ability to search. How it is displayed in a new ticket.

Additional stakeholder input.

**Comment by ntallman** [comment]
If any file has machine-readable text, it should be extracted and added to a full-text index.

**Comment by awead** [comment]
Details:
* create file of extracted text using the text use type, and add to the file set
* index extracted text in the file set
* don't extract text if it is provided in the bag
* only preform the extraction on the representative file set in the work, which contains a pdf of the work

**Comment by cam156** [comment]
From what I can tell right now is I search for the file name it finds the FileSet (or File) associated with the name, but then the show page for the FileSet( or File) throws an error.  There does not seem to be any current search capability for a work with certain FileSet information.  With the scope of this ticket I would have expected the work/fileset search to already be set up.

**Comment by awead** [comment]
Converted to an epic. It originally had 8 points.
