### ISSUE TITLE
Objects without Collections

### ISSUE THREAD

**Issue by ntallman** [psu-libraries/cho#140]
As a Special Collections curator,
I would like to have some digitized material added to CHO without being part of a collection,
So that we can make discreet/one-item special collections material available online. 

Ben G.

**Comment by cam156** [comment]
Have objects that are a part of the the system could be associated with a default collection

This could have implications on the permissions and workflow.

Palmer Art Museum Admin Set, Special Collections Admin Set, Life Sciences Admin Set

**Comment by ntallman** [comment]
Objects without collections should be included in the index and retrievable via search by end users, but they do not need to be on the UI as part of any collections. I.e., the can be searched and found, but not browsed, someone must know it's there. Akin to a private URL.

CHO Permissions should be set by the uploader.

**Comment by ntallman** [comment]
Discussed this user story with Ben. All objects must belong to a collection. The story arose in the context of one-off patron digitization requests. These cases can be handled in two ways: 
  - Create an Archival Collection, save the object to that collection, make private, send the user a token-based authenticated URL to view and download the object.
  - Save the object to the Special Collections Library Collection (not an Archival Collection) for user access, restricted as necessary. If the whole collection is later digitized, the object may be moved to an Archival Collection.

No need to have this an explicit user story, closing.
