### ISSUE TITLE
Archival Citations in Metadata

### ISSUE THREAD

**Issue by ntallman** [psu-libraries/cho#148]
As a Civil War history researcher
I would like to know where the original archival object I am viewing is located
In order to plan a visit to use the original archival material

Eric N.

Dependent on value being available in the metadata.

Related: #130

**Comment by ntallman** [comment]
@lmballinger this is a metadata MAP issue and not a developer issue. Can you please take this into account when working on the base MAP? I'm taking this off MVP milestone.

**Comment by awead** [comment]
Validate that base MAP has fields for shelf location information or other pertinent metadata regarding location.

**Comment by ntallman** [comment]
This is not a system feature, this is an implementation detail for the metadata manager.
