### ISSUE TITLE
System wide metadata defaults

### ISSUE THREAD

**Issue by bmrgoldman** [psu-libraries/cho#15]
As a metadata specialist, I would like cross-repository metadata templates so that I can apply metadata requirements across the whole repository.

**Comment by cam156** [comment]
Required fields across collections.  Each collection can have additional items, but these requirements must be present

**Comment by cam156** [comment]
This is related to the Base Metadata Application Profile (MAP)  that @lmballinger is working on.  How do we enforce the information in MAP.

**Comment by cam156** [comment]
https://psu.app.box.com/file/211247382460 - Is the content DM MAP.  Any required fields here should be required in CHO.  The CHO MAP will be larger.

**Comment by cam156** [comment]
Related to #57 & #16.  The fields define here will be the one people can choose from for the templates.

System Metadata Workflow: https://psu.app.box.com/notes/218648875937

**Comment by cam156** [comment]
This will include defining what autocompletes are available to the user in the template creation.

**Comment by cam156** [comment]
* Assume we have a FieldValidatorFactory that takes the validation type and returns a class that can perform that validation.

* Assume we have a FieldPresentorFactory that takes the display transformation name and returns a class that can transform the value to return the presented value.

* Assume we have a ControlledVocabularyFactory that takes the controlled vocabulary name and returns a controlled vocabulary

* Field Type: string, text, date, number (are there other types)

* Required: required, recommended, optional

```
rails generate scaffold MetadataField label:string field_type:integer required:integer
validation:string multiple:boolean controlled_vocabulary:string default_value:string display_name:string display_transformation:string
```

**Comment by cam156** [comment]
- [x] Create a model object to store the information
- [ ] CRUD Operations
- [ ] Export as CSV
- [ ] Import CSV
- [ ] FieldValidatorFactory
- [ ] FieldPresentorFactory
- [ ] ControlledVocabularyFactory

**Comment by awead** [comment]
This is now called the data dictionary, see #323
