### ISSUE TITLE
PSU User Role

### ISSUE THREAD

**Issue by ntallman** [psu-libraries/cho#172]
As a Penn State community member,
I would like to login with my normal credentials,
So that I don't need a separate account to save items in CHO.

Child of #798

**Comment by ntallman** [comment]
Shibboleth not cosign

**Comment by cam156** [comment]
Need to switch out our devise modules to use Shibboleth

**Comment by ntallman** [comment]
Enhancement to #350 that allows additioanl role -- logged in user for things like saving citations and bulk download.

**Comment by ntallman** [comment]
The minimal implementation may use LDAP and psu_dir gem.

The ideal implementation would use Shibboleth/OneId. This would give us the most flexibility in terms of granular permissions later on. Would need to wall off Friends of PSU, Hershey Medical, and Penn College from accessing restricted collections. (Unless stakeholders sign off.) Would also enable us to achieve #181 and #195. ITECH is looking at using OpenAthens for Shibboleth/OneId.

If implementing using the second option, this ticket should be repointed.

**Comment by ntallman** [comment]
Related: #798

**Comment by awead** [comment]
TODO:
* use Cancancan gem to determine access level (admin vs. non-admin)
* restrict access to menu options: manage, create work and collection
* read-only access to everything else
