### ISSUE TITLE
Import metadata from spreadsheets (17 points)

### ISSUE THREAD

**Issue by bmrgoldman** [psu-libraries/cho#20]
As a metadata specialist, 
I would like to batch import metadata from a spreadsheet,
so that I don't have to enter metadata object-by-object through the GUI 

Related: #17, #207

**Comment by cam156** [comment]
Loading a collection for the first time it will have a path to the content

Loading for an existing collection it will just be the metadata.  This will not change the existing content.

**Comment by cam156** [comment]
The metadata and the content will be in the same directory on the server

**Comment by cam156** [comment]
This should be transactional.  If one item fails then the entire batch should fail.

**Comment by nrm149** [comment]
Story Dependencies: Export story may need to happen then import and definitions about what the objects are.

**Comment by cam156** [comment]
Dependant #15 & #57

**Comment by cam156** [comment]
I am putting this into the ready column because the concept of reading in a CSV file, matching a binary file and validating the metadata should be independent the way we store the data.  Although only half of the would be available to work on I do believe much of the design could be done prior to picking  a backend.

**Comment by cam156** [comment]
There may be code in ScholarUC

**Comment by cam156** [comment]
https://github.com/uclibs/scholar_uc/issues/599

**Comment by ntallman** [comment]
This ticket is highly related to #360 and should be closed simultaneously.

**Comment by ntallman** [comment]
Comments from Ruth on the structure of the CSV:

> It would be in the structuring of the CSVs, such as the first time it goes in it'll have to tell you which collection it should be associated with, how multi-value fields are handled, etc. In terms of different schemas, that would just be something like the header (where | is a spreadsheet break, although these would be CSVs)
> 
> dc:title | dc:date |  mrel:ivr
> 
> or the field names being used in Valkyrie or whatever's needed. And then if just the metadata were reloaded, it would just have to say that it should be associated with a particular work already existing.
