### ISSUE TITLE
Benchmarking Collections

### ISSUE THREAD

**Issue by ntallman** [psu-libraries/cho#203]
As a repository manager,
I need CHO to be able to handle collections with 250K+ objects,
So that the platform is stable.

**Comment by ntallman** [comment]
Test Hyrax to see if it can handle. Go from there.

**Comment by ntallman** [comment]
Largest collection in CONTENTdm is [Horowitz Transaction Publisher Archive](https://collection1.libraries.psu.edu/cdm/landingpage/collection/transaction). It contains 385,117 items, however some of those items are compound objects. Total object count is 243,348.

**Comment by awead** [comment]
Test this when we have code for collections and works. Write a script or rake task that build a collection with 300K items in it.

**Comment by awead** [comment]
Steps:
1. Run a test with 1 million empty works
2. Run a test with 1000 works each containing a 50 mb tiff (~50 GB total)

Each test should be repeatable for future releases, and resulting performance should be tracked.
