### ISSUE TITLE
Smoke Test Scenarios

### ISSUE THREAD

**Issue by awead** [psu-libraries/cho#209]
In order to investigate Hyrax's ability to handle lots of files and works, we need to "smoke test" a few scenarios to get an idea of how well it might perform in the real world.

1. Work with 400K small files, ~ 1 MB
2. Work with 400K large files, ~ 1 GB
3. Collection with 300K works

**Comment by cam156** [comment]
@awead  Are you planning to clear the repository between the large and small files?  Timing comparisons would not be relevant between a first set and a last set of the system is loaded differently

**Comment by awead** [comment]
Report is avaiable here http://awead.github.io/fedora-tests/

**Comment by awead** [comment]
PR needs to double-check

**Comment by awead** [comment]
Child of #203
