### ISSUE TITLE
Combine Facets

### ISSUE THREAD

**Issue by ntallman** [psu-libraries/cho#224]
As a smart user, 
I want to be able to select more than one facet (limit), 
so that I can get the quantity and type of results that I want. 

Henry P.

**Comment by ntallman** [comment]
Related: #34

**Comment by awead** [comment]
@ntallman We can currently select more than one facet. Search results are ANDed, meaning the results contain all of the facets selected. Does that resolve this ticket?

**Comment by ntallman** [comment]
It does resolve this ticket. Done! There are no points, but do we need to throw this into this milestone?

**Comment by awead** [comment]
@ntallman no, I think it's ok to just close this and move on.
