### ISSUE TITLE
Create Specific Object Types In the System

### ISSUE THREAD

**Issue by cam156** [psu-libraries/cho#239]
Need and object type for each of the following:
 * Still Image
 * Audio/Video
 * Maps 
 * Document
 * Generic 

Child of #57

**Comment by cam156** [comment]
related to #15

**Comment by awead** [comment]
Assumes that each class will have files attached, and with Valkyrie, will require additional classes for complete implementation. This ticket also covers the controllers, views, routes, as well as other required components for complete implementation.

**Comment by awead** [comment]
To demonstrate:
1. Go to http://localhost:3000/work_objects/new
2. Create a work without a title
3. Fill in title, click create
4. Search for the title
5. Facet on work type
6. Click title in search results
7. Click edit
8. Remove title, click update
9. Add new title, click update
10. Click edit again and delete work

**Comment by cam156** [comment]
DCMI Type Vocabulary could be thought about.  Do we need to match these for later?
