### ISSUE TITLE
Collection Level Object for storing Collection Configuration (Templates)

### ISSUE THREAD

**Issue by cam156** [psu-libraries/cho#247]
This object will store templates that have been defined during collection creation for the collection as a whole and each allowed object type for the collection.

Templates will include fields and order of the fields for each Object Type.

Child of #16

Acceptance criteria: We have an object that holds all the information that is created in the forms for #250 and #249.

**Comment by cam156** [comment]
Language Fields translate from code to display name: ENG translates to English, JAP translates to Japanese

**Comment by awead** [comment]
List of fields for the collection and a list of work types for the collection.

**Comment by awead** [comment]
This is similar to #240, only for a collection, and that ticket should probably be done first and this one can be based off of it.

**Comment by awead** [comment]
Dependent on:
#102, #56 and #98

Related to: #193

**Comment by ruthtillman** [comment]
I think this is one which can just go.

**Comment by awead** [comment]
No longer applicable.

**Comment by awead** [comment]
removed 8 points
