### ISSUE TITLE
Create a work type template wireframe

### ISSUE THREAD

**Issue by cam156** [psu-libraries/cho#248]
For each field within a template we want to be able to specify and update the following:
 * Mark a field as 'Required for publishing', 'Recommended' or 'Optional' (this is shown to the user via a badge or something)
 * Validation from the Base MAP will be inherited for this property or Overridden here 
     * Especially Date validation (Display may be in a different format from entry)
     * Language code ( EN vs for display English)
* Mark Field as Singular Field or Multiple Field (Multiple fields will be displayed in the order entered)
* Controlled Vocabulary could be either inherited from the Base Map or redefined for this field
   * displayed as a literal and stored as a URI
   * specify if the auto complete is the only valid value or if auto complete is a suggestion and any value is allowed
* Apply default field value
* Assign field display name
* display transformations
* other options under # 3 in https://psu.app.box.com/notes/254001359476

Any of the above options may be inherited from the data dictionary.

Child of #320, related to #240.

**Comment by mtribone** [comment]
I need a little clarification on the last bullet item. What does "display transformations" mean?

**Comment by awead** [comment]
Need to define a ticket that is a model for this data.

**Comment by mtribone** [comment]
[collection_template_workflow.pdf](https://github.com/psu-libraries/cho/files/1519219/collection_template_workflow.pdf)

**Comment by awead** [comment]
For curated collections, does it make sense to choose object types and workflow?

**Comment by awead** [comment]
Notes:
* core fields will be listed as bullet points to inform the user that these fields will be automatically included
* order fields, both additional and core, as a whole set
* add new page to order the selected fields; this would be a new page 2
