### ISSUE TITLE
Create Collection Creation/ Edit Wireframe

### ISSUE THREAD

**Issue by cam156** [psu-libraries/cho#249]
Create a wireframe to create a new collection (or edit) and define the collection template information as well as additional steps in the workflow:
https://psu.app.box.com/notes/218572150655

Ordering of fields for the collection template is needed.

child of #16

Dependent on #248

**Comment by awead** [comment]
May need separate wireframes for each collection type: Archival, library, and curated. Archival and library collection types may be similar enough and not require separate forms. Curated is likely to be the most different.

**Comment by ruthtillman** [comment]
See the Collection note: https://psu.app.box.com/notes/254001863649

**Comment by awead** [comment]
Closed, see #324 for changes.
