### ISSUE TITLE
Apply template to edit form for work in a collection

### ISSUE THREAD

**Issue by cam156** [psu-libraries/cho#252]
How do we apply the defined template to modify the edit/create form for a work when it is created within a collection

The template should define what fields are displayed for editing, the order of those fields, the type of widget for edit (including autocomplete) and the labels for those fields. 

dependent #247
child of #16

**Comment by cam156** [comment]
Required fields do not stop objects from being saved, but do stop object from being published

**Comment by cam156** [comment]
Language Fields translate from code to display name: ENG translates to English, JAP translates to Japanese

**Comment by awead** [comment]
The base map will default to alpha ordering of the fields if the template makes no changes to that order.

**Comment by awead** [comment]
No longer applicable

**Comment by awead** [comment]
removed 8 points
