### ISSUE TITLE
Create Collection Object Types

### ISSUE THREAD

**Issue by cam156** [psu-libraries/cho#258]
We have 3 types of collections within the system: Archival Collection,  Library Collection, Curated Collection

Each collection will have differences, but what are those?

**Comment by cam156** [comment]
@ntallman has a google doc about the different collection types: (fill in url here)

**Comment by awead** [comment]
Just create the ruby class

**Comment by awead** [comment]
Should each collection type be a different class, or a property on a single Collection class? The latter option is consistent with work objects, which will have their type set as a property.

**Comment by awead** [comment]
We're proceeding with three classes, one each for the type of collection.
