### ISSUE TITLE
Investigate UI options

### ISSUE THREAD

**Issue by awead** [psu-libraries/cho#261]
For CHO's user interface should we borrow/steal from Hyrax or write our own UI from the ground up?

* Bootstrap 4 https://v4-alpha.getbootstrap.com/
* Material Design https://material.io/
* polaris.shopify.com
* CSS grid w/ flexbox

What are the development and support costs?

**Comment by cam156** [comment]
How does Blacklight interact with any of work with Blacklight.  Replace  css from Blacklight.

How difficult would it be to update blacklight to use Bootstrap 4 or Material Design

**Comment by ntallman** [comment]
https://bootswatch.com/paper/ -- Material Design for Bootstrap

**Comment by cam156** [comment]
Mix of community querying and a little bit of implementation.

**Comment by ntallman** [comment]
Other Material Design frameworks: 
- http://www.material-ui.com/
- https://material-components-web.appspot.com

**Comment by mtribone** [comment]
Looks like with this pull request https://github.com/projectblacklight/blacklight/pull/1690 we can explore some of these frameworks

**Comment by mtribone** [comment]
https://mdbootstrap.com/material-design-for-bootstrap/

**Comment by mtribone** [comment]
https://github.com/rubysamurai/material_design_lite-sass
