### ISSUE TITLE
Implement EDTF for Dates

### ISSUE THREAD

**Issue by awead** [psu-libraries/cho#267]
This is track discussions and decisions about what date formats to use and how to enforce them. At this point, we're preferring EDTF formats, and using both Date and String types to store them.

Note, there is a Ruby EDTF implementation: https://github.com/inukshuk/edtf-ruby

This ticket should also include the work required to validate EDTF dates in the UI based on the field type in the data dictionary.

Tasks:

* implement an EDTF data type in Valkyrie
* add the data type to CHO for date fields

**Comment by ruthtillman** [comment]
EDTF++

**Comment by ntallman** [comment]
Will need to store EDTF and display string.

**Comment by awead** [comment]
Store EDTF in the json within the Valkyrie resource, then display its string representation on the page. EDTF values will be validated on save.

If we create a Valkyrie EDTF type, we can use the change set to validate it. Values will be indexed in Solr using their defaults, _tesim and _ssim.

**Comment by ntallman** [comment]
> Values will be indexed in Solr using their defaults, _tesim and _ssim.

Does this mean that users will be able to perform date searches as expected? Or is another ticket needed for working out a strategy to allow for advanced date searching (ranges, specific dates, fuzzy dates, etc.)
