### ISSUE TITLE
Test MVP 1 for accessibility compliance

### ISSUE THREAD

**Issue by awead** [psu-libraries/cho#305]
* run WAVE accessibility toolkit
* keyboard navigation
* voiceover

Child of #165

**Comment by awead** [comment]
Ideally, this would include time spent with a visually impaired individual who can use a screen reader with the system and identify any issues.

**Comment by mtribone** [comment]
twitter typeahead in the search may prove to be challenging when testing accessibility.

**Comment by mtribone** [comment]
Tabbing through the interface

- [ ] Navigable items receive focus

**Comment by awead** [comment]
This was pointed at 5.
