### ISSUE TITLE
Creating new collections

### ISSUE THREAD

**Issue by awead** [psu-libraries/cho#321]
As a metadata librarian
I want to create new collections and configure them for workflow and visibility

This will be done when I can create a new collection, add metadata about the collection from a set of pre-existing fields, assign a workflow, and a visibility. For more detailed workflow, see https://psu.app.box.com/notes/254001863649

Formerly #16

**Comment by awead** [comment]
See note: https://psu.app.box.com/notes/254001863649

**Comment by awead** [comment]
To complete this epic we need to close:

- [ ] Collection Level Object for storing Collection Configuration #247 
- [ ] Create wireframes:
  - [ ] Create Collection Creation/ Edit Wireframe #249

    **note:** no index view is needed because access will be through the collection edit page
 1. Implement Collection Creation/ Edit Wireframe #250
 1. Implement a Metadata Field Definition Template Wireframe #251
 1. Apply template to edit form for work in a collection #252
 1. Apply template to view page for work in a collection #253

**Comment by mtribone** [comment]
[collection_creation_revDec13.pdf](https://github.com/psu-libraries/cho/files/1556586/collection_creation_revDec13.pdf)

**Comment by ntallman** [comment]
@mtribone Re: admin metadata for collections, see #161 for current fields. We might want to include only the "core" fields identified in #161 on the collection creation template. (Minus Dates for APTrust and DPN.)
