### ISSUE TITLE
Define core set of fields

### ISSUE THREAD

**Issue by awead** [psu-libraries/cho#322]
As a metadata librarian
I want to specify a set of core fields that are available to every object (both works and collections)
So that we have a minimum level of description across the repository

**Comment by ntallman** [comment]
For MVP, collections will only get the coreMAP fields. Future enhancement will be to add additional fields from data dictionary.

**Comment by awead** [comment]
We'll need a list of what the fields are from @ruthtillman and @lmballinger. After which the fields will be defined in code.

**Comment by ntallman** [comment]
Ruth and Linda will try to get the coreMAP to the dev team by Jan 29, but it might be latter. Moving this story to a lower priority within the sprint to give them some more time, if needed.

**Comment by awead** [comment]
Once we have the list, we'll need to decide how to implement this. Currently, the data model has a boolean field in the data dictionary to indicate if a field is core or not. Are there are other way we need to consider?

**Comment by awead** [comment]
Use CSV import process in SeedMAP
