### ISSUE TITLE
Faceted Discovery

### ISSUE THREAD

**Issue by DanCoughlin** [psu-libraries/cho#34]
As a user,
I would like to browse the content of the repository based on existing metadata fields (creator, subject, format/genre, library, rights),
So I can further refine my search results.

**Comment by ntallman** [comment]
@DanCoughlin Do you mean you want to refine search results with facets? Or starting from all content browse with filters? (Which would just be a "*" search.)

**Comment by mtribone** [comment]
Base metadata profile to be provided by Linda. Faceted expects to be an "OR". Keep the "AND" if that is the default. Blacklight Advanced Search not in Hyrax but exists. 

Just want facets. Nathan to edit ticket.

**Comment by ntallman** [comment]
Related: #224

**Comment by awead** [comment]
@ntallman we have facets currently. Does that mean this is done? Otherwise, what does done look like?

**Comment by ntallman** [comment]
As it reads explicitly, I don't think this ticket is done. Done looks like facets for creator, subject, format/genre [work type is sufficient], library, and rights).  Creator and subject are currently not facets. Library is an admin metadata field we don't have now and rights will probably need enhancement to facet correctly, so they might need to be removed to another ticket. 

However, our app supports the ability to facet and that's really the spirit of this user story. We have #459 to control faceting via data dictionary, so we can then turn on whatever facets we need later and the library and rights metadata will shake out. So, I'm okay if we close this.

**Comment by awead** [comment]
Removed 3 points and closed.
