### ISSUE TITLE
Basic User Role (MVP only)

### ISSUE THREAD

**Issue by ntallman** [psu-libraries/cho#350]
Some of our MVP user stories rely on a very basic user role structure.

- Admin user -- anyone who is in the specified UMG
- Public user -- anyone not logged into MVP CHO

Some fields (and possibly other things) will be restricted from public users, only visible to admin users.

Users will be authenticated using LDAP credentials and their access determined using UMGs.

Precedes: #102 
Depends on: #379

**Comment by awead** [comment]
For users who are logged in but not allowed access, the response should be 403 instead of 401. Change the allow_admins method in ApplicationController.
