### ISSUE TITLE
Investigate Multiple Item Input techniques

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/cho#352]
Review  Simple Form, Cocoon, Nested Rails, JS techniques for form creation and processing.

- Accessibility
- Make sense to developer for maintenance
- Ease of Testing

**Comment by awead** [comment]
Related to https://psu.app.box.com/notes/270243120124

**Comment by awead** [comment]
For MVP, we will not use JS and instead use form/controller interactions to add additional empty fields. Later, when we add JS, we can progressively enhance this interface.
