### ISSUE TITLE
Upload File(s) to a Single Work Object

### ISSUE THREAD

**Issue by ntallman** [psu-libraries/cho#359]
As a digital production technician,
I would like to upload a file or files to a work object,
So that the content may be ingested to CHO and made available online.

**Comment by awead** [comment]
Depends on #364

**Comment by awead** [comment]
Includes creating the necessary Valkyrie resources to store the file, as well as any other Ruby classes. FIles will be stored in local temp space for now.

**Comment by awead** [comment]
File upload is not working in QA.
