### ISSUE TITLE
Bulk Upload of File(s) to Multiple Work Objects

### ISSUE THREAD

**Issue by ntallman** [psu-libraries/cho#360]
As a digital production technician,
I would like to upload files for many digital objects at once,
So I can upload my daily work every night.

As a digital production manager,
I would like to batch create new works with metadata and files,
So that I can upload works, with their files, at the same time.

Enhancement to #238. See File Specification for Import

Related: #544 (closed duplicate, some notes there)

**Comment by awead** [comment]
@ntallman how does this differ from #359?

**Comment by ntallman** [comment]
#359 is batch upload to a single work-object (probably through the work creation UI). This is about batch upload of many work-objects, perhaps along the lines of what I mentioned with a directory of subdirectories and a CSV with metadata and relative paths to the objects.

**Comment by awead** [comment]
@ntallman #359 should be UI-only. An API can be ticketed separately. This ticket, however, will need to be unpacked.

**Comment by awead** [comment]
This ticket could be resolved in #20, assuming  that adding files to each work is included in the implementation.

**Comment by ntallman** [comment]
Functionally this user story is accomplished when #545 is completed.
