### ISSUE TITLE
Investigate file upload tools

### ISSUE THREAD

**Issue by awead** [psu-libraries/cho#364]
Sufia and Hyrax still use CarrierWave for the backend and a jQuery file upload plugin for the UI. Do we still want to use that combination? We should explore what other options exist.

**Comment by cam156** [comment]
Options for investigation

- [ ] [carrierwave](https://www.ruby-toolbox.com/projects/carrierwave)
- [ ] [shrine](https://www.ruby-toolbox.com/projects/shrine)
- [ ] [remotipart](https://www.ruby-toolbox.com/projects/remotipart)

There are a few other gems in ruby toolbox, but they do not have recent releases

**Comment by cam156** [comment]
There could also be some javascript options to look at based on the java script framework chosen

**Comment by cam156** [comment]
Remotipart only has documentation for Rails 3.  Going to skip it.

Shrine documentation suggests it is similar to 
- [ ] Dragonfly
- [ ] Refile

**Comment by awead** [comment]
Uploading folders, and retaining their structure, would be a nice bonus. @ntallman will provide further details if nested folders should be nested works or not.

**Comment by cam156** [comment]
| No AR | processing chain | restartable upload integration | File Folder Structure | html5 ui
-- | -- | -- | -- | -- | --
Shrine | yes | yes | tus (https://twin.github.io/resumable-file-uploads-in-ruby/) | yes (slightly harder to configure than the rest) | yes
CarrierWave | yes | yes | no built in integration | yes | yes
draginfly | yes | yes | no built in integration | yes | yes

**Comment by ntallman** [comment]
I really like that tus (via Shrine) has built-in checksums to mitigate dropped bits on transfer. +1!

**Comment by cam156** [comment]
We have chosen shrine becuase of its extensibility and the example integration with TUS.
