### ISSUE TITLE
Required to save option

### ISSUE THREAD

**Issue by awead** [psu-libraries/cho#373]
Fields like "title" should be a required field when saving a new resource. This should be distinct from "required to publish" where a field can be absent, but the resource can still be saved.

What done looks like:
1. Add "required" option to list of requirement designations in the data dictionary
2. The "required" option is interpreted by the form to show which fields are required to save the resource
3. If a required field is blank, the error message should be rendered by the client using HTML5. Note: collections are already done this way with respect to "Title" but works are not.

**Comment by cam156** [comment]
This is using required to publish to mark required: https://github.com/psu-libraries/cho/blob/9b7db9cd69e1beac3ed60fd88de9b172851e6a01/app/cho/data_dictionary/fields_for_change_set.rb#L14-L15

It should use the new required option
