### ISSUE TITLE
Create wireframes for work and collection relationships

### ISSUE THREAD

**Issue by awead** [psu-libraries/cho#382]
Create a set of wireframes that show how:
1. Creating new works and selecting a collection for them
2. Creating a new work from the collection page

**Comment by mtribone** [comment]
I've added buttons to the collection creation page, but made them a "little less" wordy. we can work on the text. Basically when you create a collection you have 3 options a) create collection b) create collection and upload submissions c) create collection and add existing submissions.

![collection_upload_add](https://user-images.githubusercontent.com/4163828/36313821-e603bd6a-1300-11e8-848c-81d3dc688d83.png)

**Comment by ntallman** [comment]
Listbox preferred for new works for MVP, knowing that autosuggest will eventually replace the mega-dropdown. 

Archival and Library Collections should not have the option to create and add existing works -- that should be reserved for Curated Collections only.

**Comment by mtribone** [comment]
Got it. Thanks @ntallman !

**Comment by mtribone** [comment]
Just a quick default listing of items in the collection to get us started.

![collection_with_submissions](https://user-images.githubusercontent.com/4163828/36392284-78344294-1578-11e8-8ed6-983e302fea2c.png)
