### ISSUE TITLE
Refactor Auto-generated Submission Form for Works

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/cho#393]
The auto-generated form for new submissions (generic, document, still image, map, moving image, audio) use `<p>` and `<br>` to layout out the form inputs and labels. It isn't the best approach for accessibility or modern best practices to layout a form. 

Please see https://github.com/psu-libraries/cho/pull/386 for a better way to refactor the form.

**Comment by awead** [comment]
Fixed by https://github.com/psu-libraries/cho/commit/5300ad0d88d89acc986a108ecc0cb4d68c4faacc
