### ISSUE TITLE
Document which persisters can be used with which resources

### ISSUE THREAD

**Issue by awead** [psu-libraries/cho#402]
Some of our resources can be persisted with any of Valkyrie's persisters. Some, however, cannot, such as the DataDictionary::Field which cannot be indexed in Solr because it has a boolean field.

We need to document which of our resources have these issues to avoid future confusion.

**Comment by cam156** [comment]
Specifically DataDictionary Fields cannot be persisted due to boolean and single value fields.  Other classes should be checked for Boolean and single value fields

**Comment by awead** [comment]
Documentation should be in the form of code comments. Distinguish between which resources can be persisted by all persisters, which should be persisted in Solr, and which can't.
