### ISSUE TITLE
Error when using back button on collection or work creation page

### ISSUE THREAD

**Issue by ntallman** [psu-libraries/cho#414]
When viewing either the create collection or create submission form, the back button at the bottom of the form throws an error of "this page does not exist". Also, the button should probably look like a button and not plain text.

**Comment by mtribone** [comment]
It isn't uncommon to separate primary, secondary, and tertiary actions with differing styles. Buttons _should_ be for actions and links _should_ be for linked content. We can certainly make them look however we'd like them to look, but just some thoughts on interactions and styles.

**Comment by ntallman** [comment]
I certainly want us to be using best practices. I'm having an existential crisis on whether "back" is an action (take me back) or a link (link to the previous page). I just thought it looked odd as is. Is there a reason we have a back button (or link) instead of relying on the browser back button? Not sure if it's a rails thing or something.

**Comment by mtribone** [comment]
@ntallman Yeah man. I feel ya. The back link is from the generated form from Rails. We can make adjustments based on what makes sense for us.

**Comment by awead** [comment]
Just remove the button/link.
