### ISSUE TITLE
Use "of" for sets instead of "member"

### ISSUE THREAD

**Issue by cam156** [psu-libraries/cho#415]
attribute :files, Valkyrie::Types::Set.of(Valkyrie::Types::ID.optional)

See samvera-labs/valkyrie/394

`member` is deprecated in favor of `of`.

**Comment by ntallman** [comment]
Related to #419?

**Comment by awead** [comment]
What's the difference between `member` and `of` and why would we want to use one versus the other? Not directly related to 419, but will be once we upgrade to Valkyrie 1.0 and all fields must sets. We might want to use `of` because Valkyrie has deprecated `member`.

**Comment by awead** [comment]
@ntallman not directly related, but we will need to change work id to be a set as per Valkyrie 1.0 requirements.
