### ISSUE TITLE
Undefined Method `edit_work_file_path' when using "previous" and "next" in Catalog

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/cho#426]
After I've created a work and am on the show page for the work, I get an error when selecting either the "previous" or "next" links.

![screen shot 2018-03-05 at 3 46 56 pm](https://user-images.githubusercontent.com/4163828/36998912-880b146c-208c-11e8-8b60-59df72905b9f.png)

**Comment by mtribone** [comment]
![screen shot 2018-03-05 at 3 47 17 pm](https://user-images.githubusercontent.com/4163828/36998936-9b88573e-208c-11e8-984c-26f4c3b5f653.png)

**Comment by awead** [comment]
Cannot duplicate.
