### ISSUE TITLE
Apply bare-bones Matomo tracker in CHO

### ISSUE THREAD

**Issue by ntallman** [psu-libraries/cho#427]
As simple as including a code snippet in a footer. No further customization at this point, just want to see what data it collects and how it can be viewed/analyzed on the PiWik backend.

#7 is a more complexed and nuanced implementation of analytics for a future release.

**Comment by ntallman** [comment]
Piwik has been renamed to Matomo. https://matomo.org/blog/2018/01/piwik-is-now-matomo/

**Comment by awead** [comment]
@ntallman will look at getting a hosted service to use until a locally-run service is deployed.

**Comment by ntallman** [comment]
APP-INT has decided to setup a Matomo server, will just be used for CHO for now. If expands to other library services, service provider will be rethought.

**Comment by awead** [comment]
After talking with @jrpatterson, the server should be ready by September, which will coincide with MVP4, so we should be able to complete this at that point.

**Comment by ntallman** [comment]
Dependent on #648 as a place to put the code.
