### ISSUE TITLE
Explore Sass organization and override methods

### ISSUE THREAD

**Issue by awead** [psu-libraries/cho#429]
Should we continue to use asset pipeline for sass and css or is there a better, different way? This ticket should explore alternatives and look at the benefits and drawbacks for each.

**Comment by awead** [comment]
* http://codeguide.co
* use scss linter
* https://cssguidelin.es/

**Comment by mtribone** [comment]
https://evilmartians.com/chronicles/evil-front-part-1

**Comment by mtribone** [comment]
https://github.com/thoughtbot/guides/tree/master/best-practices#sass

**Comment by mtribone** [comment]
https://sass-guidelin.es/

**Comment by mtribone** [comment]
https://getbootstrap.com/docs/4.0/getting-started/theming/
