### ISSUE TITLE
Collection-ID Field on Work Create Page

### ISSUE THREAD

**Issue by ntallman** [psu-libraries/cho#443]
"Member of collection ids" should have a required label and validation

![image](https://user-images.githubusercontent.com/549591/37231314-ae7071f4-23b8-11e8-9fe9-235783b6312c.png)

**Comment by awead** [comment]
To fix:
* rename "collection" to "member_of_collection_ids" in data dictionary
* create a "system collections" controlled vocabulary
* display HTML5 datalist controlled vocabulary in form
* remove explicit member_of_collection_ids in models, change sets, and forms, and utilize the data dictionary term instead
* update dictionary term to be "required"

**Comment by awead** [comment]
Related to #489
