### ISSUE TITLE
Public Users

### ISSUE THREAD

**Issue by ntallman** [psu-libraries/cho#447]
As a member of the public,
I would like to browse and search for collection and works in CHO,
So that I may see and use digital library and archival collections.

Done looks like login not required to view publicly-visible works and collections.

Child of #798
Blocked by #172

**Comment by awead** [comment]
Steps:
* investigate Valkyrie's access controls
* enable setting of groups, users, and visibility on resources
* enforce access controls via Solr searches as well as at the object-level
* investigate uses of cancancan gem and blacklight-access-controls (do we still want to use these?)

**Comment by nrm149** [comment]
Will need further discussion around splitting this epic up

**Comment by awead** [comment]
* Verify that non-authenticated users can access resources in read-only mode. Public users will have more limited access when #830 and the rest of this epic complete.
* public users should not see management, create collection, and create work links
