### ISSUE TITLE
Explore upgrading to Blacklight 7

### ISSUE THREAD

**Issue by awead** [psu-libraries/cho#457]
Determine the work load and impact of upgrading to Blacklight 7.

Change the gem version, run any generators, and see what happens!

**Comment by mtribone** [comment]
https://getbootstrap.com/docs/4.0/migration/#summary

**Comment by mtribone** [comment]
Valkyrie depends on hydra-access-controls which depends on blacklight-access-controls. We would need to update blacklight-access-controls in order to use Blacklight 7.

**Comment by mtribone** [comment]
Updating CHO to use Valkyrie 1.0.0 bypasses the dependency issues, but a) doesn't let you save non-array properties and b) has extracted derivative support to https://github.com/samvera-labs/valkyrie-derivatives

**Comment by awead** [comment]
Todo:
* update to Valkyrie 1.0.0, see #466
* update the layout to use Bootstrap 4

Derivative changes isn't an issue at this point.
