### ISSUE TITLE
Update layout to use Bootstrap 4

### ISSUE THREAD

**Issue by awead** [psu-libraries/cho#467]
Use the default Blacklight layout that supports Bootstrap 4. This includes the update to Blacklight 7.

**Comment by cam156** [comment]
Dependent on #466

**Comment by mtribone** [comment]
Running through the migration docs: https://getbootstrap.com/docs/4.0/migration/

**Comment by mtribone** [comment]
Items to compare and address if needed:
- [ ] Default checkboxes and radio buttons both have matching HTML structure
- [ ] Button groups with data-toggle use data attributes and `.btn-group-toggle`
- [ ] Choose file inputs and changes to Sass variable and `.custom-file-label`
- [ ] Input groups and buttons now have prepend and append for text and such
- [ ] Removed $badge-color variable and its usage on `.badge`
- [ ] Renamed `.table-inverse` and `.thead-inverse` to `.*-dark` and `.*-light`
- [ ] Responsive tables now generate classes for each grid breakpoint
- [ ] Switched from `px` to `rem` and global type size is now 16px
- [ ] Non-responsive usage of Bootstrap is no longer supported
- [ ] Flexbox!
- [ ] Updated grid class names and a new grid tier. Every tier bumped one level. xs, sm, md, lg, and xl
- [ ] Dropped panels, thumbnails, and wells for cards
- [ ] Dropped Glyphicons

**Comment by mtribone** [comment]
Specific changes by component: https://getbootstrap.com/docs/4.0/migration/#by-component
