### ISSUE TITLE
Large Collection Support -- Test Load Time for Collection Show Page

### ISSUE THREAD

**Issue by ntallman** [psu-libraries/cho#471]
We need to make sure the load time for large collection show pages is quick. I just tried loading the 1,000,000,000 work collection on QA and it was really slow. We should write tests to make sure we aren't introducing changes that increase the load time of the collection show page or at least give us a heads up if performance is poor.

**Comment by awead** [comment]
https://github.com/psu-libraries/cho/wiki/Release-Process#run-benchmarks
