### ISSUE TITLE
Work Landing Page Enhancements

### ISSUE THREAD

**Issue by ntallman** [psu-libraries/cho#482]
As a remote scholar using primary source materials in CHO,
I would like to easily tell how to download a single file for the entire work on the page I am viewing,
So that I can quickly download what I need and begin my research.

In addition, it would be helpful to see a sample image from the work and know how I can download one or more high-resultion images of individual pages, should I need them.

Also, instead of Files for the heading to the list of file sets, please use Parts.

**Comment by ntallman** [comment]
I think @mtribone may have already added thumbnails to works? (Or was that just file sets?)

Re: the downloads and files, was thinking of a download button for the representative file for the work, if present. Works could have hundreds of file sets, unordered lists could get unruly. We might want to link out to a new page where a table of file sets. The table could have the identifier, title, date, and thumbnail. It could also have a link to the fileset show page. (Bonus: each row could have a checkbox for bulk download of file sets.)

**Comment by awead** [comment]
TODO:
* change "Files" heading to "Parts"
* suppress representative file set in work listing
* button to download the representative access file ("Download work")
* button to download text file ("Download plain text")
* thumbnails are already visible
