### ISSUE TITLE
Use Relative Path for CSV Import

### ISSUE THREAD

**Issue by ntallman** [psu-libraries/cho#490]
Using a relative path allow the use of network storage for staging files. Path will be relative to network storage share. Will need to establish network share and be aware of quota, doesn't have too large now, but will when in production. Maybe 100 GB for now? Network Share will need to be configurable so digital production staff can map a network drive.

**Comment by ntallman** [comment]
Network share will contain a directory for each collection, the directory will contain subdirectories for each work named using the local identifier for the work.

```
/cho_staging
    /pstsc_01822
        /pstsc_01822_3acd94bbf7fe36d14007bd7a5a8b00d3
        /pstsc_01822_93b33fa2ecf9631ff07472a52945f86b
```

**Comment by awead** [comment]
Done will be when we can create new works from a files uploaded to the server's local filesystem and referenced from the CSV import file. This should also include a configuration option to set the location for the files.

Relative path would look like: `pstsc_01822/pstsc_01822_3acd94bbf7fe36d14007bd7a5a8b00d3`

Dry run should report change set errors such as a file not found at its relative path.

**Comment by ntallman** [comment]
Child of #544

**Comment by cam156** [comment]
I added the csv_basepath to application.yml out on cho-qa, but since we can not copy items to it, it will be hard to demo.

**Comment by awead** [comment]
We can demo this once #541 is done.

**Comment by awead** [comment]
This was demoed at the MVP 3 retro
