### ISSUE TITLE
Map Identifiers to Member ID

### ISSUE THREAD

**Issue by ntallman** [psu-libraries/cho#491]
Libraries use a standardized naming convention for collection-level identifiers. Users should be able to specify the local collection-level identifier and the app should automatically map it to the correct Valkyrie ID. Collection-level identifiers should NOT map to curated collections, archival and library only. Identifier field needs to contain unique values across the app.

Related to #408
Blocked by #514
Blocked by #443

**Comment by nrm149** [comment]
- update data dictionary to include global identifier flag

**Comment by nrm149** [comment]
- where is the id coming from?
- how is it generated?
- does it have to be unique to a collection or everything?

**Comment by ntallman** [comment]
ID is assigned by library staff during digital collection building process and will be included in the descriptive metadata. All works and collection will have a unique identifier assigned. Ex: pstsc_01822 for a collection and pstsc_01822_88dsf8sdfsdff98sdf8sdfsdf8 for a work in that collection.

These identifiers will also be useful for integration later on. The last section in the work identifier is the refID in ArchivesSpace.

**Comment by cam156** [comment]
This should be store in: https://github.com/psu-libraries/cho/blob/master/config/data_dictionary/data_dictionary_production.csv#L12

**Comment by cam156** [comment]
related to #514

**Comment by awead** [comment]
Details:
* add the library-based id to the "identifier" property in the data dictionary
* enable CHO to search and return resources using the "identifier" property

**Comment by awead** [comment]
@ntallman can you expand on "Collection-level identifiers should NOT map to curated collections, archival and library only." Does that mean curated collections don't have identifiers?

**Comment by ntallman** [comment]
@awead Bad phrasing on my part. Curated collection will have identifiers, though they will likely look quite different. 

Works need to have a primary/home collection. That's really what is being set with the collection (member_of_collection_id/valkyrie_id) field in the metadata and why it's mapped to the local collection identifier, because that's how people will refer to it. But, only library and archival collections can be a primary/home collections. Curated collections are really just exhibitions and so should not be the primary collection for a work.
