### ISSUE TITLE
Unable to update existing resources

### ISSUE THREAD

**Issue by awead** [psu-libraries/cho#508]
We're getting a 'forbidden' error when updating resources.

**Comment by awead** [comment]
Need to be able to reproduce this in QA.

**Comment by ntallman** [comment]
This doesn't seem to be a bug anymore? I'm able to update works in QA.

**Comment by awead** [comment]
@ntallman yeah, I think I fixed this in af2911324682405d348a344ca0c9c15a5c3eba88. All we needed to do was allow works without files.
