### ISSUE TITLE
Change Collection Membership on Work

### ISSUE THREAD

**Issue by ntallman** [psu-libraries/cho#539]
As a cataloger,
I would like to change the collection to which a work belongs,
So that I can correct a mistake I made when I first accidentally chose the wrong collection.

Done looks  like: collection membership field displaying on work edit page.

Blocked by #443

**Comment by awead** [comment]
This could "magically" resolve once #443 is done.

**Comment by ntallman** [comment]
The user must manually delete existing value and remove the cursor from the field before data list of collections renders again.
