### ISSUE TITLE
Enable uploading of files to the QA server via scp

### ISSUE THREAD

**Issue by awead** [psu-libraries/cho#541]
In order to test #490, and while we're waiting for Samba functionality, we should enable access to the choweb1qa via ssh/scp so specific users such as @ntallman can upload files directly to the server and then test ingesting them into Cho via CSV import.

**Comment by ntallman** [comment]
Child of #544

**Comment by awead** [comment]
Talk to Jim about getting ssh access to @ntallman

**Comment by awead** [comment]
After talking with Justin, the Samba share should be available by end of September after CHO is migrated to the new Nomad cluster. This ticket can be closed if #492 is resolved within this timeframe.

**Comment by awead** [comment]
The samba share is available, we're just working out the problems with permissions.
