### ISSUE TITLE
Instructions for resetting QA

### ISSUE THREAD

**Issue by awead** [psu-libraries/cho#543]
From time to time, it's necessary to reset the QA server with new seed data. We should have instruction for logging into the servers and running the commands necessary for doing this. These commands will also be the same for benchmarking.

**Comment by informaticianme** [comment]
Clearing persistent data from a scholarsphere instance reference: https://sites.psu.edu/dltdocs/?p=4311

**Comment by awead** [comment]
https://github.com/psu-libraries/cho/wiki/Release-Process#resetting-qa
