### ISSUE TITLE
Create a processor class

### ISSUE THREAD

**Issue by awead** [psu-libraries/cho#551]
Controls how files are processed. They are attached to a work type and include steps for actions such as characterization with FITS and text extraction with Tika.

Details:
* investigate existing patterns, including dry-ruby, and Tom Johnson's processor chain work in Hydra
* modify Work::Type to include an array of processors
* define the base class that will eventually call out to the different processors like 
* defines a "runner" that executes the task

Child of #545

**Comment by cam156** [comment]
Looked at both the new code in Hyrax and dry-rb and both are utilizing http://dry-rb.org/gems/dry-transaction/ for a similar desire.

**Comment by awead** [comment]
Implementation details:
* implement dry-transactions to ingest new files into CHO
* updating, replacing, or deleting files can be addressed later (we can leave in the operation classes, though)
* creation operation should take one _or more_ files, put them into a FileSet and add them to the work
  * Sub-task: update the Work resource have file set member ids
  * Sub-task: move files attributes and other Shrine-related code from Work::Submission to Work::FileSet
  * Multi-file upload via GUI is out of scope
* add the file set to the work
* remove file-creation code from the ChangeSetPersister

**Comment by cam156** [comment]
This ticket was a team effort. @awead finished up the processing class PR, which was merged this morning.
