### ISSUE TITLE
GUI upload of files or bags to works

### ISSUE THREAD

**Issue by awead** [psu-libraries/cho#553]
As a user, I would like to be able to upload either a single file, or a bag of files to a work.

The distinction  between regular file and bag will be done via mime type: an uploaded zip file is a bag.

Files that are not bags will be added to the work as a single file set with only one Work::File and no additional derivatives. If a zip is provided, it will exacted, verified as a bag, and processed accordingly, including creation of one or more file sets and their included derivatives.

This process will duplicate what's happening in #549, but will only be for updating or creating individual works in the GUI.

Child of #545

**Comment by ntallman** [comment]
MVP -- use radio buttons to indicate if preservation file or zipped bag. Will only contain files and file sets for a single work, the work that is described in the metadata on the form.

**Comment by mtribone** [comment]
Sectional Interface exploring error reporting for zipped bags on the same page just like the metadata. 

![gui-file-upload](https://user-images.githubusercontent.com/4163828/42576059-9a02ea06-84ef-11e8-8c4e-e6df2f89d671.png)

**Comment by mtribone** [comment]
Save and import option that matches the workflow from the CSV Import Dry Run for files and zips in the GUI.

![save-import-file](https://user-images.githubusercontent.com/4163828/42576197-cdba7698-84ef-11e8-8a00-a38b4148449e.png)

**Comment by ntallman** [comment]
@awead see second comment on this ticket
