### ISSUE TITLE
add new metadata fields

### ISSUE THREAD

**Issue by lmballinger** [psu-libraries/cho#56]
As a metadata specialist,
I need to be able to add new metadata fields to existing collections, either with a uniform metadata value or as blank fields, 
So I can include additional information at any time.

**Comment by kestlund** [comment]
RDF or form?

**Comment by informaticianme** [comment]
This is adding metadata for not the collection level but rather applying to all objects within the collection, as well as the metadata template for that collection.

**Comment by ntallman** [comment]
Related: #16

**Comment by ntallman** [comment]
Comment from Karen: "Part of this may be how the templates are stored. You may want to ask Ryan Wick, Oregon State, for a screenshare demo of how this is done in Oregon Digital and what does not work well.  (It’s nice to have some experience from others to test for us.  :-) )"

**Comment by awead** [comment]
This now should be reframed as a mechanism for defining a new field that applies to all works in the collection. This is not about adding a new field to collection.

**Comment by ntallman** [comment]
This ticket is no longer needed. Things like "Donor statement" will be in the data dictionary and on all works. If it needs to be used for a collection, it can be, otherwise it can be left blank.

**Comment by awead** [comment]
Removed 8 points.

**Comment by ntallman** [comment]
Can also be achieved via CSV batch edit
