### ISSUE TITLE
format specific metadata templates

### ISSUE THREAD

**Issue by lmballinger** [psu-libraries/cho#57]
As a metadata manager, 
I need to be able to make format-specific metadata templates, 
so metadata creators have a consistent set of metadata fields, appropriate for that format, to start a new project.

**Comment by kestlund** [comment]
Formats and what else for templates and workflow.

**Comment by ntallman** [comment]
Any need for collection-specific templates?

**Comment by cam156** [comment]
Still Image, Video, Maps, Audio, Document & other  would have separate metadata standards

**Comment by cam156** [comment]
We will have work type (object type) based on format of the files in the work.  The human makes a determination based on the main entity, or nested work that have the specific types of data contained.   This is based on content of the object not the mime type of the object.  Topographical Map would be a genre of MAP.

**Comment by cam156** [comment]
Tickets for epic completion:
  1. Create Specific Object Types In the System #239
  1. Create a Object Type Template Model #240
  1. Create Object Type Template Edit Form wireframe #241 
  1. Implement Object Type Template Edit Form wireframe #242
  1. Create View Object Type Template Wireframe #243
  1. Implement View Object Type Template Wireframe #244 
  1. Create a Object Type Template Index View Wireframe #245
  1. Implement a Object Type Template Index View Wireframe #245

**Comment by awead** [comment]
Closed, replaced with #320
