### ISSUE TITLE
Acknowledgements on Collection Landing Page

### ISSUE THREAD

**Issue by ntallman** [psu-libraries/cho#572]
As a metadata librarian/cataloger/collections librarian, when describing a collection;
I would like to record and name the contributions of the people doing the curation, digitization, description, migration, and other work which has led to the collection becoming available in CHO;
so that all may be recognized for their contributions to the collection.

Ruth K-T.

Child of #483

**Comment by awead** [comment]
TODO:
* create "acknowledgements" property in the data dictionary, as a optional text field
* assign acknowledgements to the collection schema
* present field in the collection show page (a.k.a. the landing page) above the listing of items in the collection
