### ISSUE TITLE
Rename batchID to batch_id in the CSV examples

### ISSUE THREAD

**Issue by awead** [psu-libraries/cho#593]
The file specification wiki page uses `batchID` to denote the column for the batch id, or the name of the zipped bag containing works for import. The application code is going to the use `batch_id` for the column name, in order to be consistent with the format of the other columns, so we ought to make that explicit here as well.

**Comment by ntallman** [comment]
@awead Is the same true for workID and collectionID?

**Comment by ntallman** [comment]
Made the changes on https://github.com/psu-libraries/cho/wiki/File-Specifications

**Comment by ntallman** [comment]
@awead Though perhaps this should be to remove batch_id altogether per #599?

**Comment by ntallman** [comment]
Changed in wiki, can be removed from wiki after #599 is closed.
