### ISSUE TITLE
Display page for file sets

### ISSUE THREAD

**Issue by lmballinger** [psu-libraries/cho#63]
As a metadata specialist I need to be able to associate (mostly administrative, technical, and preservation) item-level metadata to each of the items/images that make up a multi-item object, so I can provide item-specific metadata for each item individually.

**Comment by kestlund** [comment]
PCDM

**Comment by DanCoughlin** [comment]
We want to allow the metadata specialist to edit metadata on the work and the fileset. Example of fileset metadata to be added by user: file name/label, and rights (which we currently do).

Other notes that may be helpful from discussion:

Example is we could have an oral history that has video, audio, and documents that are in the oral history. They may have different metadata associated with each of them.

A generic work that contains an image work, a video work, and audio work. The metadata will apply to the work and not to the file set (with the exception of wanting to perhaps store a label for each file: preservation, access, etc.).

**Comment by awead** [comment]
This was a pre-Valkyrie ticket and now needs some refinement. We don't have file sets yet, so we'll need to address that before we can get to this issue.

**Comment by awead** [comment]
File object will need rights. For example, a non-redacted TIFF would not be made public, whereas its redacted version would be public. This serves CHO's larger goal of making high-quality TIFFs available to the public.

Related #205

**Comment by ntallman** [comment]
Dependent: #408

**Comment by awead** [comment]
Descriptive-level metadata and other admin. metadata that is yet to be organized, could be applied to the file set, which would mean all the metadata in the file set would apply to each derivative file in the set.

**Comment by ntallman** [comment]
This user story if functionally accomplished when #582 is complete.

**Comment by awead** [comment]
To complete this, the ticket should also include:
* updating file set metadata via GUI
* updating file set metadata via CSV import
* displaying file sets #634

**Comment by awead** [comment]
Create a show page for displaying the metadata and file information associated with a file set. This should be linked from the work show page, under what currently is called "Files."

**Comment by mtribone** [comment]
Create the view for the PNG file until further notice.
