### ISSUE TITLE
Rendering Failure messages from operations

### ISSUE THREAD

**Issue by awead** [psu-libraries/cho#643]
Controllers are not able to interpret Failure messages sent from operations. Currently, the messages are just strings, but we might want to put them into the `errors` object and attach it to the change set so that they can be displayed as a flash message, like we are currently doing with other types of errors.

Related to #553

**Comment by awead** [comment]
This may have been fixed in #618.

**Comment by mtribone** [comment]
Look through all transactions that are called by controllers from a UI action.

**Comment by mtribone** [comment]
Error Handling within Operations
- https://github.com/psu-libraries/cho/blob/master/app/cho/transaction/operations/file/characterize.rb#L19
- https://github.com/psu-libraries/cho/blob/master/app/cho/transaction/operations/file/create.rb#L15
- https://github.com/psu-libraries/cho/blob/master/app/cho/transaction/operations/file/create_temp_file.rb#L17
- https://github.com/psu-libraries/cho/blob/master/app/cho/transaction/operations/file/save.rb#L17
- https://github.com/psu-libraries/cho/blob/master/app/cho/transaction/operations/file_set/extract_text.rb#L25
- https://github.com/psu-libraries/cho/blob/master/app/cho/transaction/operations/import/extract.rb#L22
- https://github.com/psu-libraries/cho/blob/master/app/cho/transaction/operations/import/work.rb#L19
- https://github.com/psu-libraries/cho/blob/master/app/cho/transaction/operations/import/zip.rb#L19
- https://github.com/psu-libraries/cho/blob/master/app/cho/transaction/operations/file_set/file_output_service.rb#L21
- https://github.com/psu-libraries/cho/blob/master/app/cho/transaction/operations/import/validate.rb#L17
