### ISSUE TITLE
Basic Footer

### ISSUE THREAD

**Issue by ntallman** [psu-libraries/cho#648]
As product owner,
I would like to be able to look at the footer in CHO and tell what version of CHO is running and when it was deployed,
So that I can always know what version is running.

Ideally, there would be a link to the release in Github, which may contain release notes. We will probably have a different strategy when in production.

**Comment by awead** [comment]
Create a link to the commit in Github using the REVISION file in the root of deploy directory. Ex. `Rails.root.join("REVISION")` but this only present in a deployed instance, and not in development.
