### ISSUE TITLE
Download Files

### ISSUE THREAD

**Issue by ntallman** [psu-libraries/cho#649]
As a user,
I would like to be able to click a link and download files attached to a fileset attached to a work,
So that I can save the file/work to my device.

Simplest implementation presents all files with a download link, though this is not the final desired solution.

**Comment by ntallman** [comment]
This might end up being accomplished in #63.

**Comment by ntallman** [comment]
If a fileset contains a _preservation_redacted file, the _preseration file cannot be downloadable/viewable by the user.

**Comment by awead** [comment]
TODO:
* add download links for every file in the file set to the file set show page
  * if a redacted preservation file is present, this is downloaded and _not_ the actual preservation file
* add a download link to each file set in the work show page
  * link downloads the service file, if present, or preservation the file

**Comment by awead** [comment]
* Add options for all the other use types except redacted preservation: front, back, admin, text, and thumbnail.
* Remove the download links on the work landing page.
* From the file set landing page, make the title of the file the link
