### ISSUE TITLE
Export Collection Metadata, Including Fileset Metadata

### ISSUE THREAD

**Issue by ntallman** [psu-libraries/cho#650]
As a metadata librarian,
I would like to be able to export the metadata for all the works (and their filesets) in a collection as a CSV,
So that I can curate, remediate, and otherwise edit the metadata for reimport OR for export for other projects.

Blocked by #582

**Comment by awead** [comment]
Details:
* expand the csv export of a collection to include all the file sets included within each work
* each file set within a work will result in another row in the csv
