### ISSUE TITLE
Batch Metadata Update (Including filesets)

### ISSUE THREAD

**Issue by ntallman** [psu-libraries/cho#651]
As a metadata librarian,
I would like to be able to upload a CSV that has updated metadata for existing works (and filesets) and have that metadata replace the stored values,
So that I can easily update metadata in batch without having to edit each record.

**Comment by ntallman** [comment]
Dupelicate of #207

**Comment by ntallman** [comment]
#207 achieves batch update via CSV, but not sure if it includes the ability to update filesets. Need to confirm.

**Comment by awead** [comment]
Related to #686

**Comment by ntallman** [comment]
Closing and merging with #686
