### ISSUE TITLE
Modeling non-descriptive metadata

### ISSUE THREAD

**Issue by lmballinger** [psu-libraries/cho#66]
As a metadata specialist,
I need a way to record non-descriptive metadata (administrative, technical, preservation) and store it in association with its objects in the repository, 
So I can use this metadata for ongoing maintenance and long-term preservation.

**Comment by kestlund** [comment]
What kind?

**Comment by ntallman** [comment]
@lmballinger This is an epic and needs to be broken down into a user story for each needed. Most technical metadata will be automatically included through file characterization.  PREMIS metadata is definitely needed, but how we need to have an implementation plan on how we use it.

**Comment by DanCoughlin** [comment]
Not sure if this is to be stored in Fedora or User Activity Stream. It seems like the User Activity Stream is acceptable for this type of information at this point and we would store characterization on the files.

**Comment by ntallman** [comment]
Related: #184

**Comment by ntallman** [comment]
Scoping the nature of this ticket to how we store non-descriptive metadata. Are all fields in the data dictionary? Separate data dictionaries for different metadata types? What are the fields needed?

**Comment by awead** [comment]
Was originally 8 points

**Comment by awead** [comment]
Descriptive and administrative metadata can live in the data dictionary, provided that they are editable by the user. So we should have an indicator in the dictionary for metadata type (i.e. admin. versus descriptive or other). The properties of additional technical, preservation, and administrative metadata,  such as predicates and display names, that is derived from automated processes, like FITS, can be defined someplace else.

**Comment by awead** [comment]
* Add an editable column to the data dictionary (true/false)
* add editable property to DataDictionary and Schema::Metadata classes
* only render editable fields in work and collection edit form
* all fields currently in the data dictionary are editable

**Comment by awead** [comment]
Add administrative and technical metadata to the data dictionary, but do not add them any schemas yet. Later work will define how the fields are implemented for editing in works or collections, and how they might be initially derived by extracting them from other sources such as fits xml.

**Comment by awead** [comment]
Points removed, was previously 3.
