### ISSUE TITLE
Incorrect error when saving a work without a file

### ISSUE THREAD

**Issue by awead** [psu-libraries/cho#673]
If I attempt to create a new work without a file, I see this error:

Save undefined method `content_type' for "":String

Instead, I should see that a file is required. The error happens at Transaction::Shared::SaveWithChangeSet, line 18.

**Comment by ntallman** [comment]
Was this fixed in #785?

**Comment by awead** [comment]
Er, yes, but I seems that we need to have files _required_ for works. Is this true or do we need to allow file-less works?

**Comment by ntallman** [comment]
We will want to have works without files. Edge-cases, but needed sometimes. As long as there are no file sets, we shouldn't get caught up in bag requirements, right?
