### ISSUE TITLE
Visibility (access level) for collections

### ISSUE THREAD

**Issue by ntallman** [psu-libraries/cho#683]
Collection edit form has the following options for visibility settings, with only the public option implemented:

## Visibility
  * Public
  * Authenticated
  * Private

All options need to be implemented and expand slightly. Options (and what the mean) outlined below.

## Access Level
  * Public Access (anyone who can get to CHO)
  * PSU Access (WebAccess authenticated users)
  * Private Access (user or group of users)

**Comment by awead** [comment]
Sub-tickets:

* Implement Valkyrie access controls -  #973 
* Implement authenticated visibility - #974
* Implement private visibility for single user  - #975
* Enable setting of access levels in CSV - #976

Note:
* absence of any access controls means public access, _if you don't know, it's public_
* collections will not govern the access controls of works (yet)
* adding additional users and groups will be in another ticket
