### ISSUE TITLE
Use Data Dictionary display name as the csv heading

### ISSUE THREAD

**Issue by awead** [psu-libraries/cho#706]
Currently, the attribute's method name or the dictionary's `label` is used for the csv header. This might create confusion now that `alternate_id` is used instead of identifier.

We could use the display name as the csv header to more closely align the displayed label for the field with its csv counterpart.

Related to #491

**Comment by ntallman** [comment]
Would we be able to handle spaces in the display names? Case sensitivity? How would this affect round tripping? I'm inclined to limit CSVs to the dictionary's `label`.

**Comment by awead** [comment]
@ntallman all very good questions. I think spaces and case sensitivity would be find. However, round-tripping would be affected if the display name changed after a csv had been exported. In the case, the csv would not import because it would have the old column name. Perhaps it's best to stick with the label, even if its name isn't all that clear.
