### ISSUE TITLE
Re-Index Facets on Change to "Index Type" in Data Dictionary

### ISSUE THREAD

**Issue by ntallman** [psu-libraries/cho#720]
When a user edits a field in the data dictionary to change the "Index Type" property to "facet' from "no_facet", and the metadata already contains values for that field, Solr must re-index to populate the facets. This should happen automatically when the change is saved.

Related to #459
Related to #689

**Comment by awead** [comment]
TODO:
* edit DD to change rights or subject from `no_facet` to `facet` and see if that results in a facet appearing
* correct the DD/CatalogController to fix if the above is not the case

**Comment by awead** [comment]
Rights statements are being faceted, but dates are not. We need to decide how we want to facet dates in general.

**Comment by awead** [comment]
Changed date_created to an edtf date.
