### ISSUE TITLE
MVP Home Page

### ISSUE THREAD

**Issue by awead** [psu-libraries/cho#739]
~~CHO needs a complete homepage with appropriate links, text, and other content to be determined after engaging with stakeholders. It is assumed that some of the content will be dynamic, depending on existing content in CHO, as well as static, and possible user-created, such as editable sections of the page, similar to what we have in Scholarsphere.~~

* CHO needs an MVP homepage that more barebones, but still elegant. A minimalistic design that emphasizes discovery. Content does not *need* to be dynamically generated for MVP. Editable blocks are not needed for MVP, at most 1 block of introductory text would be needed. 
* Merging related ticket (#714): Update the home page view to include an h1 for accessibility and code quality.

Inspiration
- [NYPL](https://digitalcollections.nypl.org/)
- [Duke](https://repository.duke.edu/dc?)
- [Oregon Digital](https://oregondigital.org/catalog/)
- [UCSD](https://library.ucsd.edu/dc/)

Related: #768

[Updated by NT]

**Comment by ntallman** [comment]
Merging related ticket (#714): Update the home page view to include an h1 for accessibility and code quality.

**Comment by mtribone** [comment]
![cho-home-2nav](https://user-images.githubusercontent.com/4163828/54930418-9ecd9680-4eed-11e9-8add-a7b73c397a33.png)

**Comment by mtribone** [comment]
![cho-home-2nav-min](https://user-images.githubusercontent.com/4163828/54930437-a856fe80-4eed-11e9-9024-4a9d55ed9d76.png)

**Comment by mtribone** [comment]
![cho-home-kee-ullered](https://user-images.githubusercontent.com/4163828/54948417-f8948780-4f12-11e9-9cac-468669a45214.png)
