### ISSUE TITLE
Work CSV Export Should be Roundtrip-able

### ISSUE THREAD

**Issue by ntallman** [psu-libraries/cho#752]
When exporting work-level metadata by appending ".csv" to the URL, it needs to include header information. It should be possible to import work and fileset metadata updates using the current UI (batch update).

Blocked by #686

**Comment by ntallman** [comment]
#686 might fix this...

**Comment by awead** [comment]
TODO:
* export column headers (data dictionary labels) in csv
* ensure that you can re-import the exported csv successfully after editing in MS excel
* use existing excel csv in the fixtures or create a new one for testing
