### ISSUE TITLE
Unauthorized page accessibility

### ISSUE THREAD

**Issue by awead** [psu-libraries/cho#768]
Screen reader doesn't seem to read the unauthorized page.

**Comment by ntallman** [comment]
What is our HTTP response on this page?
* 401 Unauthorized really means *unauthenticated*, which is this case here.
* 403 Forbidden really means *unauthorized*, which is not the case here.

We might want to avoid the text "unauthorized".

**Comment by awead** [comment]
@ntallman They're getting a 401 here. It's a very basic page without much or any markup:

https://github.com/psu-libraries/cho/blob/master/app/devise/unauthorized_controller.rb#L8

This is probably why the screen reader can't read it. The 403 page is much nicer:

https://github.com/psu-libraries/cho/blob/master/public/403.html

We can have a page like this for the 403 because we've gotten past Devise, the gem that does the authentication, and we're "in" the Rails app, we just don't have access to anything. The 401 error is a much more basic page and doesn't use the full Rails app. It was the simplest solution. We could probably flesh out the page a bit more, or just build a full controller so we can render a nicer looking page. We'll have to do that eventually anyway.

**Comment by ntallman** [comment]
For now, we could probably add some basic HTML code improvements to increase the accessibility of this page. At the same time, perhaps changing the wording as I suggest above. 

Will we need to build this full controller before we migrate everything over and are in full swing? If so we should ticket that epic and if the quick fix isn't tenable, this ticket could be dependent on the full controller epic.

**Comment by ntallman** [comment]
#739 may make this ticket unnecessary

**Comment by ntallman** [comment]
#447 did away with the page that prompted this original ticket. We have new unauthorized pages (which do return 403 responses) added with #912 that will be tested with future accessibility testing.
