### ISSUE TITLE
Rendering dates in edit forms as they're stored in Postgres

### ISSUE THREAD

**Issue by awead** [psu-libraries/cho#794]
When rendering the edit form for a resource, date fields are shown using a Ruby-style date-to-string conversion, as opposed to the value that is stored in Postgres.

## Examples

From the edit page, user enters `2019-01` and updates the resource. The display page shows `datetime-2019-01-01T00:00:00.000Z` which is the solr value. When the user re-edits the resource, the value in the edit form is `2019-01-01 00:00:00 UTC` instead of `2019-01`.

The value that was originally entered is in Postgres, it should just be shown to the user instead of the solr-adjusted one.

**Comment by ntallman** [comment]
Related/solved by #687
