### ISSUE TITLE
Ordering of Works

### ISSUE THREAD

**Issue by ntallman** [psu-libraries/cho#802]
Works, file sets, and files are not sorted properly on display. One approach would be to sort on the identifier, regardless of what is displayed. That might be easier for MVP. Or, preserve the order from the CSV? (Both, depending on ingest method?) Implementing [ORE ordering](https://github.com/duraspace/pcdm/wiki/PCDM-2.0#ordering) might be the 1.x solution?

**Comment by awead** [comment]
TODO:
* sort works on identifier
* verify works are displayed in a collection in the order according to their identifier (alternative_ids field)
