### ISSUE TITLE
Configure Basic Search in Blacklight

### ISSUE THREAD

**Issue by ntallman** [psu-libraries/cho#804]
When searching, the query matches on all fields, regardless of what dropdown is selected. This should be configured to search the field selected in the dropdown. For basic search, dropdown should be limited to core fields. All fields should be the default selection.

**Comment by awead** [comment]
Related to #833

**Comment by awead** [comment]
TODO:
* configure CatalogController to search on the individual fields specified in the dropdown list
* limit the dropdown list to core fields
* default searches to All Fields

**Comment by awead** [comment]
Description search seems to be faulty. When searching on description, we're getting results when the field is empty. See collection pstsc_01822 for United Mine Workers.

**Comment by mtribone** [comment]
It appears that the text extraction of file sets or parts is affecting the core field search. The core fields should be configured to search *only* those fields and not return the extracted text for fileded searches when there isn't a match.
