### ISSUE TITLE
Collection CSV Metadata Export Doesn't Include Work Type

### ISSUE THREAD

**Issue by ntallman** [psu-libraries/cho#817]
When exporting a CSV of metadata for a collection of works (and their file sets) the work type is not included in the CSV and should be. 

Related: #752

**Comment by awead** [comment]
TODO:
* fix broken listing of works in collections
* write additional tests that check for listing of works in collection display pages
* adjust csv export of collections to include work types
* work types will be their labels, ex. (Image, Still Image, etc.)
