### ISSUE TITLE
Batch Agent Creation Bugs

### ISSUE THREAD

**Issue by ntallman** [psu-libraries/cho#820]
- CSV export of agents uses "Surname" and "Given Name" as column headers; CSV import for agents expects "surname" and "given_name" -- not round-tripable; should match style used for works (surname, given_name)

- Rows and colums in the CSV Status table during Agent Import Preview are mis-aligned
![image](https://user-images.githubusercontent.com/549591/52365643-f4211780-2a15-11e9-9a27-fb73d75c6d28.png)

**Comment by awead** [comment]
TODO:
* verify this is not related to the BOM issue in Excel
* only allow labels for the column and not display name
