### ISSUE TITLE
Duplicate Identifiers Bug

### ISSUE THREAD

**Issue by ntallman** [psu-libraries/cho#824]
I accidentally made a duplicate collection for the work, not realizing old data would remain when a new branch was deployed. I assigned the same identifier (alternate_id) for a new collection and CHO didn't complain. The identfier (alternate_id) field maps to the valkyrie property that is supposed to be unique

- https://cho-qa.libraries.psu.edu/catalog/763b12bd-2add-4321-a0b8-1afe984cafff
- https://cho-qa.libraries.psu.edu/catalog/2bff54a4-03e3-4e1a-a171-2d8cc079d6cc

**Comment by ntallman** [comment]
If this is a bug, maybe it shouldn't be? Thinking about the valkyrie property. If you had to delete a work and then later add the same work, it would have the same local identifier. If Valk thought it needed to be universally unique, wouldn't that mean it should block you using the same identifier? We would have to use the same local identifier. This may be symptomatic of our approach to multiple managing identifiiers.

**Comment by awead** [comment]
TODO:
* investigate for possible Valkyrie bug, and report as needed
* if this is a bug in Valkyrie, fix it in the Valkyrie gem
* if it is not a bug in Valkyrie fix it locally
* verify that a user cannot create a collection with the same alternate identifier

**Comment by awead** [comment]
Valkyrie _assumes_ that your alt. ids are unique, so it's up to us to do the enforcement.
