### ISSUE TITLE
Assume representative thumbnail

### ISSUE THREAD

**Issue by ntallman** [psu-libraries/cho#827]
If there is no representative thumbnail, CHO should use the thumbnail from the first file set as the representative thumbnail (if present or generated). Almost like the representative thumbnail was a symbolic link to the thumbnail from the first file set.

This way, if thumbnails were only generated for each file in the workflow, one will still display in the catalog and on landing pages, etc.

**Comment by awead** [comment]
TODO:
Grab the first file set in the work with a thumbnail. This could be the first or second file set, or whichever has the thumbnail.
