### ISSUE TITLE
Implement access controls for objects

### ISSUE THREAD

**Issue by awead** [psu-libraries/cho#830]
Enable fine-grained permissions on works, collections, and other objects in CHO using access controls.
* investigate Valkyrie's and Blacklight's access controls
* enable setting of groups, users, and visibility on resources
* enforce access controls via Solr searches as well as at the object-level

Child of #798

**Comment by awead** [comment]
Enable fine-grained permissions on works, collections, and other objects in CHO using access controls.

* investigate Valkyrie's and Blacklight's access controls
* enable setting of groups, users, and visibility on resources
* enforce access controls via Solr searches as well as at the object-level

**Comment by ntallman** [comment]
Is this covered by more recent tickets?

**Comment by awead** [comment]
Fix in #683
