### ISSUE TITLE
Imported works do not show as members of a collection

### ISSUE THREAD

**Issue by awead** [psu-libraries/cho#833]
After importing works via bag+csv, the display page for the collection does not list the contained works. The problem seems to be that the `alternate_id` property is used for the `member_of_collection_ids` field. The link between work and collection is correctly made: the work points to the collection. However, the inverse query in `Collection::WithMembers` doesn't seem to find the contained works within the collection.

TODO:
* additional testing of imported collections to verify display of works
* verify existing collection feature tests include display of works

**Comment by awead** [comment]
This could be a bug in Valkyrie, depending on whether or not we should be able to find inverse references using an alternate id. See https://github.com/samvera-labs/valkyrie/issues/696

**Comment by ntallman** [comment]
I believe this bug is referenced in the solution to #817. If it is separated into this ticket, we might need to adjust points on #817 or make this part of an epic.

**Comment by awead** [comment]
@ntallman thanks for catching this. I've just edited the tickets to remove the overlap.
