### ISSUE TITLE
SSH Access to CHO Servers for CHO PO

### ISSUE THREAD

**Issue by ntallman** [psu-libraries/cho#838]
As CHO product owner,
I would like to be able to SSH to CHO servers,
So that I can clear out files, check logs, and perform other similar activities without taking up the dev team's time.

Some future tickets like #825 and #829 will help with these issues, but in the meantime, SSH would allow me to do what I need to. Also, there may be other, similar things in the future.

**Comment by ntallman** [comment]
If it helps, I had SSH access to the CONTENTdm servers and currently use a VM for digital preservation work, which I regularly SSH to. I have sudo rights on both, but don't necessarily need sudo here, as long as I have the necessary permissions.

**Comment by awead** [comment]
This will need to go through @jrpatterson with approval from @DanCoughlin. #829 is slated for this upcoming sprint. I think #825 could be addressed via other means such as #835 which would track errors, or other administrative tools.
