### ISSUE TITLE
Indexing Bugs

### ISSUE THREAD

**Issue by ntallman** [psu-libraries/cho#839]
Filenames and identifiers (alternate_ids) don't seem to be indexing anymore.

All of the folloing should but do not [return this work](https://cho-qa.libraries.psu.edu/catalog/ad18ffe7-5f84-4324-9d93-ad98933c9b3a)
- Identifier: [pstsc_09844_e15ca556987b120ed80a50444194464a](https://cho-qa.libraries.psu.edu/?utf8=%E2%9C%93&search_field=title&q=pstsc_09844_e15ca556987b120ed80a50444194464a)
- Identifier: [pstsc_09844_e15ca556987b120ed80a50444194464a_00003_001](https://cho-qa.libraries.psu.edu/?utf8=%E2%9C%93&search_field=title&q=pstsc_09844_e15ca556987b120ed80a50444194464a_00003_001)
- Filename: [pstsc_09844_e15ca556987b120ed80a50444194464a_00003_001_text.txt](https://cho-qa.libraries.psu.edu/?utf8=%E2%9C%93&search_field=title&q=pstsc_09844_e15ca556987b120ed80a50444194464a_00003_001_text.txt)

**Comment by awead** [comment]
Possibly related to #833

**Comment by awead** [comment]
To reproduce:
Search for filename or an identifier and it should works.

**Comment by awead** [comment]
Searching the complete filename works, however, partial names like pstsc_06352_b01f01 do not. Verify that Solr config change is made in QA. You should not see the ICU tokenizer for tesim fields.

**Comment by awead** [comment]
After the correct solr upgrade this is working, but the search result ranking might be misleading.
