### ISSUE TITLE
Creator Roles

### ISSUE THREAD

**Issue by ntallman** [psu-libraries/cho#87]
As a metadata editor,
I want to express the role of a creator, especially when multiple creators are present,
so that users can understand why these names are associated with the object.

Example: 

CREATOR:
Johnson, Philip
CREATOR ROLE:
Architect

CREATOR:
Olin, Laurie
CREATOR ROLE:
Landscape Architect

CREATOR:
Moon Systems, Inc.
CREATOR ROLE:
Lighting Designer

CREATOR:
Baker Associates
CREATOR ROLE:
Builder

Henry P.

**Comment by informaticianme** [comment]
Creator role should be an 'open field' but likely tied to one controlled vocabulary or another. For order of creator and order of creator role, order is not important, only necessary that association between creator and creator role is intuitively apparent.

Samvera community is working on use of creator as fedora object. This will provide the ability to relate sub-fields to a particular creator (e.g. multiple creator roles for a particular creator). Also could pull creator sub-fields from external sources.

There will need to be exploration into how creators-as-fedora-objects will be implemented. There was mention of dates(birth,death) and whether there should be two records, one for creator and one for the item, where the item would then have a reference to the creator object as well as a controlled vocab term for that creator's roles.

The 5point implementation would be to stuff a fedora field with, say, comma delineated strings or just post data to a relational database.

**Comment by awead** [comment]
Use a Valkyrie nested resource, which would created another dimension to the json that's stored in the Postgres resource. Ex:
```
{ 
  title: "Sample Resource",
  creator: [
    { name: "Joe Bob", role: "author" },
    { name: "Jane Doe", role: "choreographer" }
  ]
  ...
}
```
This might be easier than having a separate Creator resource related to a work via an ids attribute.

**Comment by awead** [comment]
Todo List:
* define Agent resource (#730)
* create linked field class (#731)
* controlled vocabulary for Agent resources (#732)
* forms for entering creators and roles (#733)
* batch import will do the same thing as the UI and reject resource with Agents that don't exist (#736)
* create Agent resources via CSV import (#737)

Future enhancement:
* person resources would apply to other fields such as contributor
* combined controlled vocabs, ex: local persons + Getty
* add creators "on the fly"

**Comment by ntallman** [comment]
Metadata librarian would prefer to have:
* creator and role stored and indexed in separate fields
* creator and role concatenated into a string via a display transformation: CREATOR,  role (see examples below)
* role should be facetable

Some valid creator fields from LCNAF or other sources will have a paraenthetical role already, so we cannot add the role in parenthesis. When a role is present, a comma, space, and value of role string should be concatenated to the value of creator.

**Creator:** Tallman, Nathan (Cartographer), engraver
**Creator:** Ballinger, Linda, photographer
**Creator:** Wead, Adam, composer

**Comment by awead** [comment]
@ntallman I asked this in email, but I'll repeat it here too. `Tallman, Nathan (Cartographer)` would effectively be `surname: 'Tallman', given_name: 'Nathan (Cartographer)'`. Is this how you intended to use the Agent resources?

**Comment by awead** [comment]
Additional metadata terms for Agent records would come from LCNAF https://www.loc.gov/marc/authority/ad100.html or MADS http://www.loc.gov/standards/mads/rdf/v1.html#MADSScheme

**Comment by ntallman** [comment]
@lmballinger Do we need to be able to preserve order in instances of multiple creators or contributors? (Or really, any time we're applying a controlled vocab, I guess.)
