### ISSUE TITLE
HTML5 Required Attributes for Inputs and Accessibility

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/cho#872]
Using the HTML5 required attribute for inputs may have some accessibility issues. The error messages floats above the form and may not be tied programatically to the input. Also the error says,"Please fill out this field" and doesn't state which form field is required in the message. Needs more review.

**Comment by mtribone** [comment]
We would need to add some custom JS in order to address the messaging and perhaps the positioning of the tooltip-style box. Perhaps we should punt. We do include aria-required as an attribute on the required inputs.

**Comment by awead** [comment]
This will be addressed in future work with form validation, but we're closing now since we don't have any specific work to do.
