### ISSUE TITLE
Change File Format and Rights to a Combo Box

### ISSUE THREAD

**Issue by mtribone** [psu-libraries/cho#874]
When editing or creating a work during the screen reader testing, the user indicated that a combo box would be better than the drop down.

**Comment by mtribone** [comment]
There have been changes to the interface since we ha the accessibility testing. File format is now a multi-field. Wonder if rights can be fed by the Data Dictionary.

**Comment by awead** [comment]
File format will be derived., and rights will use a controlled vocabulary, which is slated to be done in other tickets.
