### ISSUE TITLE
Collection Facet Not Updated When Collection Title Is Changed

### ISSUE THREAD

**Issue by ntallman** [psu-libraries/cho#876]
When editing an existing collection title, the collection facet is not updated with the new title. The new title is indexed however because it can be searched.

**Comment by mtribone** [comment]
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/4163828/58134063-a3fc4880-7bf3-11e9-83ae-615c2873262a.png">

**Comment by mtribone** [comment]
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/4163828/58134083-b4142800-7bf3-11e9-895f-62fe83e413bd.png">

**Comment by mtribone** [comment]
I believe that this has been fixed.
