### ISSUE TITLE
Hiding Items/Groups of Items from Public Display

### ISSUE THREAD

**Issue by ntallman** [psu-libraries/cho#88]
As a collection manager, 
I want the ability to hide an item or group of items from the public, 
so that I can deal with emergencies such as disgustingly egregious production errors, takedown requests from alleged rights holders, etc.

Henry P.

This should be doable in hyrax using admin sets and view/visibility settings.

Child of #791

**Comment by awead** [comment]
We might need a separate predicate, or process, that marks the record as unavailable, but preserves the existing visibility. If we only used visibility to implement this, we'd loose whatever the previous setting was after marking it as _private_.

**Comment by ntallman** [comment]
Related: #230

**Comment by awead** [comment]
Implemented in #994
