### ISSUE TITLE
Add Blacklight gallery

### ISSUE THREAD

**Issue by awead** [psu-libraries/cho#895]
Displays search results in a "Gallery" format

Child of #483

**Comment by rschenk** [comment]
The most recent release of the blacklight-gallery gem does not support Blacklight 7.

The current HEAD of the master branch of the blacklight-gallery repo _does_ have support for blacklight 7, but there is no release tag. We could install the gem straight off the repo's master but it seems like it may be more prudent to punt on this until it's officially released?

**Comment by awead** [comment]
I'll enquire about the status of the release. Let's hold off until we know.

**Comment by awead** [comment]
From code4lib#blacklight: "We aren't using BL 7 for our project that uses blacklight-gallery yet.
So, we did some work to show that BL 7 would work in theory, but I'm not sure we've done extensive testing."

Given that, I think we can go ahead and use master, provided it doesn't completely blow anything up, and see how it works out. If we find bugs, we can ticket them either here or in the bl-gallery repo.
