### ISSUE TITLE
Investigate Blacklight Sessioning

### ISSUE THREAD

**Issue by ntallman** [psu-libraries/cho#917]
What is blacklight doing in terms of sessions and history tracking? Users have a history when not logged in and can bookmark items. #444 persists a year later. How long is this user data held? Where is it held? Can it be disabled? Why should or shouldn't it be disabled?

We also need to be sure we are complying with [UL-AD14](https://libraries.psu.edu/policies/ul-ad14)

**Comment by awead** [comment]
Done looks like: answer the above questions, and provide an answer to whether we're complying with UL-AD14.

**Comment by mtribone** [comment]
Saved Searches
- deprecated in Blacklight 7
- https://github.com/projectblacklight/blacklight/wiki/Saved-Searches

**Comment by mtribone** [comment]
1. Guest user holds data just for the current session
2. ActiveRecord-based just for the session?
3. Yes
4.

**Comment by mtribone** [comment]
Moving the compliance question to https://github.com/psu-libraries/cho/issues/1046
