### ISSUE TITLE
Failures during text extraction are not logged

### ISSUE THREAD

**Issue by carolyncole** [psu-libraries/cho#928]
https://github.com/psu-libraries/cho/blob/master/app/cho/transaction/operations/file/save.rb#L28

It is also not logged here: https://github.com/psu-libraries/cho/blob/master/app/cho/transaction/operations/import/work.rb#L61

Likely this code should be extracted into a step so that it can be reused in multiple operations.

**Comment by awead** [comment]
This would let NewRelic know about it, but we might also want to extend that a bit into a kind of internal ticketing system than keeps track of operations that need to be re-run.

**Comment by cam156** [comment]
Sort of a duplicate of #908

**Comment by awead** [comment]
Fixed in #908
