### ISSUE TITLE
UTF-8 Cataloging

### ISSUE THREAD

**Issue by ntallman** [psu-libraries/cho#93]
As a metadata specialist,
I need to be able to upload and export textual data in Unicode format 
so that the integrity of texts—especially texts in non-Roman languages—including diacritics and special characters, is maintained and the data is shareable across silos.

Jeff E.

Additional user story from Catherine A. 
As a curator I want to use diacritics in metadata so that the metadata will not be turned in to random symbols once uploaded into the system. 

Related? #52

**Comment by ntallman** [comment]
Many people copy/paste or import from MS Office products that use ISO 8859-X (Western Latin), this usually results in invalid character encoding because most web apps use UTF-8, so special characters rarely appear correctly. Would be nice if CHO converted everything to UTF-8 as it was saved.

**Comment by informaticianme** [comment]
Could provide a tool-tip on input form to suggest particular pasting behavior. One possibility is to employ validation upon form's input submission. Ideally, validation should happen on the client side and there may be javascript libraries that could help with that effort.

**Comment by awead** [comment]
Use Faker gem's random UTF-8 method to generate string of random UTF-8 characters in tests. We tried this earlier and ran into #480 so there'll need to be some parsing done for each field.

**Comment by awead** [comment]
https://github.com/stympy/faker/blob/master/doc/default/string.md

**Comment by awead** [comment]
How to capture any instances of bad encoding that can't be corrected?

Use Cases:
* sanitizing csv
* sanitizing GUI input

TODO:
* Test user Faker
* validate user input a la https://github.com/psu-stewardship/scholarsphere/blob/develop/app/services/encoding_service.rb
* report any incorrect encoding via a validation to the user

**Comment by awead** [comment]
Legacy or other machine-derived CSV files could have incorrectly-encoded data in them that would likely be caught during the initial dry-run step; however, the error messages might not be informative. We could consider attempting to encode these on upload and/or provide more meaningful errors messages if needed.

**Comment by cam156** [comment]
There is a todo in the metrics code for use of the faker gem, which seems highly related to this ticket: https://github.com/psu-libraries/cho/blob/master/app/cho/metrics/collection.rb#L65
