### ISSUE TITLE
Repeatable Metadata Fields

### ISSUE THREAD

**Issue by ntallman** [psu-libraries/cho#98]
As a metadata manager,
I need to be able to make some metadata fields repeatable,
so multiple values are easier to process.

Linda B.

**Comment by informaticianme** [comment]
A.k.a. Multi-Valued Fields. Order is not important, alpha sort order should suffice.

**Comment by cam156** [comment]
![screen shot 2017-12-06 at 11 47 22 am](https://user-images.githubusercontent.com/1599081/33673622-4a4fa36a-da7b-11e7-98c4-d627ed5637a0.png)

**Comment by mtribone** [comment]
So far the only repeatable form field _without_  javascript that I can find:
https://rbudiharso.wordpress.com/2010/07/07/dynamically-add-and-remove-input-field-in-rails-without-javascript/

**Comment by awead** [comment]
We will use old-style controller-backed solutions which can be progressively enhanced later.
